"""Model-version detection + automatic full re-index trigger (D-05/D-06/D-07).

The currently active embedding model name is persisted in .sync/model_version.json.
On startup, if the persisted model differs from settings.embedding.model, the
collection is dropped and re-created (so vectors generated by the new model are
consistent), and all source records are upserted again.

First-run semantics: when the file does not exist, no mismatch is reported; the
file is written after the first successful index run.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from config.settings import AppConfig

from .schema import create_collection_if_missing
from .upsert import upsert_records, UpsertResult
from sources import build_source_adapter
from embeddings import build_embedding_adapter

logger = logging.getLogger(__name__)

# Lives on the sync_data volume mounted at /app/.sync (see docker-compose.yml from Plan 03-01).
MODEL_VERSION_PATH = Path("/app/.sync/model_version.json")


def read_stored_model(path: Path = MODEL_VERSION_PATH) -> str | None:
    """Return the persisted model name, or None if the file does not exist or is unreadable."""
    if not path.exists():
        return None
    try:
        with path.open("r") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Could not read %s: %s — treating as missing.", path, exc)
        return None
    model = data.get("model")
    if not isinstance(model, str) or not model:
        logger.warning("model_version.json present but 'model' field is missing/invalid; treating as missing.")
        return None
    return model


def write_stored_model(model: str, path: Path = MODEL_VERSION_PATH) -> None:
    """Persist the active model name. Creates parent directory if missing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    with tmp.open("w") as fh:
        json.dump({"model": model}, fh)
    tmp.replace(path)  # atomic on POSIX
    logger.info("Persisted active model %r to %s", model, path)


def _drop_collection(client, name: str) -> None:
    """Drop the collection if it exists. v4 API: client.collections.delete(name)."""
    if client.collections.exists(name):
        logger.info("Dropping Weaviate collection %r (model change detected).", name)
        client.collections.delete(name)
    else:
        logger.info("Collection %r does not exist; nothing to drop.", name)


def _full_reindex(client, app_cfg: AppConfig) -> UpsertResult:
    """Drop → recreate schema → fetch all records → upsert.

    Raises on schema-creation or fetch failures (caller decides whether to update
    model_version.json based on success/exception).
    """
    _drop_collection(client, app_cfg.weaviate.collection)
    create_collection_if_missing(client, app_cfg.weaviate, embedding_type=app_cfg.embedding.type)

    embedding_adapter = build_embedding_adapter(app_cfg.embedding)
    source_adapter = build_source_adapter(app_cfg.source, app_cfg.sync, app_cfg.weaviate)
    logger.info("Fetching all records from source.type=%r for full re-index.", app_cfg.source.type)
    records = source_adapter.fetch_records()
    logger.info("Source returned %d records; upserting...", len(records))

    return upsert_records(client, records, app_cfg.weaviate, app_cfg.source.type, embedding_adapter)


def check_and_handle_model_change(client, app_cfg: AppConfig, state_store=None) -> bool:
    """Compare current embedding model vs persisted; trigger full re-index on mismatch.

    Returns True if a re-index was performed, False otherwise.

    If ``state_store`` is provided and a re-index is triggered successfully, the
    store is cleared so the next incremental sync re-builds hashes for the new
    model's index rather than skipping records with stale hashes.

    Failure semantics (per plan's <failure_semantics>):
      - First run (no file): write the file after lifespan completes initial setup;
        do NOT trigger re-index.
      - Mismatch + re-index succeeds: write new model name.
      - Mismatch + re-index fails: log loudly, do NOT update file, do NOT crash the app.
    """
    current_model = app_cfg.embedding.model
    stored_model = read_stored_model()

    if stored_model is None:
        logger.info(
            "No persisted model_version found (first run). Writing %r as active model; "
            "no re-index needed.",
            current_model,
        )
        try:
            write_stored_model(current_model)
        except OSError as exc:
            logger.warning("Could not write %s on first run: %s", MODEL_VERSION_PATH, exc)
        return False

    if stored_model == current_model:
        logger.info(
            "Embedding model unchanged (current=%r stored=%r); no re-index needed.",
            current_model, stored_model,
        )
        return False

    logger.warning(
        "Embedding model changed: stored=%r current=%r → triggering full re-index.",
        stored_model, current_model,
    )
    try:
        result = _full_reindex(client, app_cfg)
        logger.info("Full re-index complete: %s", result)
        write_stored_model(current_model)
        if state_store is not None:
            try:
                state_store.clear()
                logger.info("StateStore cleared after model-change re-index.")
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not clear StateStore after model-change re-index: %s", exc)
        return True
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "Full re-index FAILED (stored model %r still recorded as active). "
            "Fix the underlying issue and restart. Error: %s",
            stored_model, exc, exc_info=True,
        )
        return False
